Repository yiisoft/router-fastroute, pull requests merged in 2019-12, with the labels that each got.

#6 Add group support
  src/FastRoute.php
Labels: type:enhancement

#10 Escape delimiter in parameter pattern
  src/FastRoute.php
  tests/FastRouteTest.php
Labels: type:bug

#15 Fix applying defaults when matching route, fix generating URL for a route with optional params
  composer.json
  src/FastRoute.php
  tests/FastRouteTest.php
  tests/UrlGeneratorTest.php
  tests/UrlMatcherTest.php
Labels: status:code review, type:bug
