Repository yiisoft/router-fastroute, pull requests merged in 2020-09, with the labels that each got.

#33 Fix tests
  src/UrlMatcher.php
  tests/DummyContainer.php
  tests/DummyDispatcher.php
  tests/UrlGeneratorTest.php
  tests/UrlMatcherTest.php
Labels: status:code review, type:test

#34 Fix host pattern bug
  src/UrlMatcher.php
Labels: status:code review, type:bug

#35 Fix tests
  tests/DummyDispatcher.php
  tests/UrlGeneratorTest.php
  tests/UrlMatcherTest.php
Labels: status:code review

#36 Add config
  composer.json
  config/common.php
Labels: status:code review
